/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as AppAuthRouteImport } from './routes/app/auth'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppJoinRouteImport } from './routes/app/join'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppAuthenticatedAccessDeniedRouteImport } from './routes/app/_authenticated/access-denied'
import { Route as AppAuthenticatedActivityRouteImport } from './routes/app/_authenticated/activity'
import { Route as AppAuthenticatedAppointmentsRouteImport } from './routes/app/_authenticated/appointments'
import { Route as AppAuthenticatedAutomationsRouteImport } from './routes/app/_authenticated/automations'
import { Route as AppAuthenticatedBillingRouteImport } from './routes/app/_authenticated/billing'
import { Route as AppAuthenticatedDashboardRouteImport } from './routes/app/_authenticated/dashboard'
import { Route as AppAuthenticatedInboxRouteImport } from './routes/app/_authenticated/inbox'
import { Route as AppAuthenticatedLeadsRouteImport } from './routes/app/_authenticated/leads'
import { Route as AppAuthenticatedRecallsRouteImport } from './routes/app/_authenticated/recalls'
import { Route as AppAuthenticatedReportsRouteImport } from './routes/app/_authenticated/reports'
import { Route as AppAuthenticatedSettingsRouteImport } from './routes/app/_authenticated/settings'
import { Route as AppPTokenRouteImport } from './routes/app/p/$token'
import { Route as ApiPublicHooksCashfreeRouteImport } from './routes/api/public/hooks/cashfree'
import { Route as ApiPublicHooksMetaLeadsRouteImport } from './routes/api/public/hooks/meta-leads'
import { Route as ApiPublicHooksMetaMessagesRouteImport } from './routes/api/public/hooks/meta-messages'
import { Route as ApiPublicHooksMetaOauthCallbackRouteImport } from './routes/api/public/hooks/meta-oauth-callback'
import { Route as ApiPublicHooksRazorpayRouteImport } from './routes/api/public/hooks/razorpay'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'
import { Route as ApiPublicHooksWhatsappRouteImport } from './routes/api/public/hooks/whatsapp'
import { Route as AppAuthenticatedPatientsIndexRouteImport } from './routes/app/_authenticated/patients/index'
import { Route as AppAuthenticatedPatientsPatientIdRouteImport } from './routes/app/_authenticated/patients/$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/app/auth',
  path: '/app/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/app/book',
  path: '/app/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/app/join',
  path: '/app/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedAccessDeniedRoute =
  AppAuthenticatedAccessDeniedRouteImport.update({
    id: '/access-denied',
    path: '/access-denied',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedActivityRoute =
  AppAuthenticatedActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAppointmentsRoute =
  AppAuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationsRoute =
  AppAuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedBillingRoute = AppAuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedDashboardRoute =
  AppAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedInboxRoute = AppAuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedLeadsRoute = AppAuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedRecallsRoute = AppAuthenticatedRecallsRouteImport.update({
  id: '/recalls',
  path: '/recalls',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedReportsRoute = AppAuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedSettingsRoute =
  AppAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppPTokenRoute = AppPTokenRouteImport.update({
  id: '/app/p/$token',
  path: '/app/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCashfreeRoute = ApiPublicHooksCashfreeRouteImport.update({
  id: '/api/public/hooks/cashfree',
  path: '/api/public/hooks/cashfree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMetaLeadsRoute = ApiPublicHooksMetaLeadsRouteImport.update({
  id: '/api/public/hooks/meta-leads',
  path: '/api/public/hooks/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMetaMessagesRoute =
  ApiPublicHooksMetaMessagesRouteImport.update({
    id: '/api/public/hooks/meta-messages',
    path: '/api/public/hooks/meta-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaOauthCallbackRoute =
  ApiPublicHooksMetaOauthCallbackRouteImport.update({
    id: '/api/public/hooks/meta-oauth-callback',
    path: '/api/public/hooks/meta-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRazorpayRoute = ApiPublicHooksRazorpayRouteImport.update({
  id: '/api/public/hooks/razorpay',
  path: '/api/public/hooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRoute = ApiPublicHooksWhatsappRouteImport.update({
  id: '/api/public/hooks/whatsapp',
  path: '/api/public/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedPatientsIndexRoute =
  AppAuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedPatientsPatientIdRoute =
  AppAuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/app/auth': typeof AppAuthRoute
  '/app/book': typeof AppBookRoute
  '/app/join': typeof AppJoinRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/access-denied': typeof AppAuthenticatedAccessDeniedRoute
  '/app/activity': typeof AppAuthenticatedActivityRoute
  '/app/appointments': typeof AppAuthenticatedAppointmentsRoute
  '/app/automations': typeof AppAuthenticatedAutomationsRoute
  '/app/billing': typeof AppAuthenticatedBillingRoute
  '/app/dashboard': typeof AppAuthenticatedDashboardRoute
  '/app/inbox': typeof AppAuthenticatedInboxRoute
  '/app/leads': typeof AppAuthenticatedLeadsRoute
  '/app/recalls': typeof AppAuthenticatedRecallsRoute
  '/app/reports': typeof AppAuthenticatedReportsRoute
  '/app/settings': typeof AppAuthenticatedSettingsRoute
  '/app/p/$token': typeof AppPTokenRoute
  '/api/public/hooks/cashfree': typeof ApiPublicHooksCashfreeRoute
  '/api/public/hooks/meta-leads': typeof ApiPublicHooksMetaLeadsRoute
  '/api/public/hooks/meta-messages': typeof ApiPublicHooksMetaMessagesRoute
  '/api/public/hooks/meta-oauth-callback': typeof ApiPublicHooksMetaOauthCallbackRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/app/patients/$patientId': typeof AppAuthenticatedPatientsPatientIdRoute
  '/app/patients/': typeof AppAuthenticatedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/app': typeof AppIndexRoute
  '/app/auth': typeof AppAuthRoute
  '/app/book': typeof AppBookRoute
  '/app/join': typeof AppJoinRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/access-denied': typeof AppAuthenticatedAccessDeniedRoute
  '/app/activity': typeof AppAuthenticatedActivityRoute
  '/app/appointments': typeof AppAuthenticatedAppointmentsRoute
  '/app/automations': typeof AppAuthenticatedAutomationsRoute
  '/app/billing': typeof AppAuthenticatedBillingRoute
  '/app/dashboard': typeof AppAuthenticatedDashboardRoute
  '/app/inbox': typeof AppAuthenticatedInboxRoute
  '/app/leads': typeof AppAuthenticatedLeadsRoute
  '/app/recalls': typeof AppAuthenticatedRecallsRoute
  '/app/reports': typeof AppAuthenticatedReportsRoute
  '/app/settings': typeof AppAuthenticatedSettingsRoute
  '/app/p/$token': typeof AppPTokenRoute
  '/api/public/hooks/cashfree': typeof ApiPublicHooksCashfreeRoute
  '/api/public/hooks/meta-leads': typeof ApiPublicHooksMetaLeadsRoute
  '/api/public/hooks/meta-messages': typeof ApiPublicHooksMetaMessagesRoute
  '/api/public/hooks/meta-oauth-callback': typeof ApiPublicHooksMetaOauthCallbackRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/app/patients/$patientId': typeof AppAuthenticatedPatientsPatientIdRoute
  '/app/patients': typeof AppAuthenticatedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/app/auth': typeof AppAuthRoute
  '/app/book': typeof AppBookRoute
  '/app/join': typeof AppJoinRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/_authenticated/access-denied': typeof AppAuthenticatedAccessDeniedRoute
  '/app/_authenticated/activity': typeof AppAuthenticatedActivityRoute
  '/app/_authenticated/appointments': typeof AppAuthenticatedAppointmentsRoute
  '/app/_authenticated/automations': typeof AppAuthenticatedAutomationsRoute
  '/app/_authenticated/billing': typeof AppAuthenticatedBillingRoute
  '/app/_authenticated/dashboard': typeof AppAuthenticatedDashboardRoute
  '/app/_authenticated/inbox': typeof AppAuthenticatedInboxRoute
  '/app/_authenticated/leads': typeof AppAuthenticatedLeadsRoute
  '/app/_authenticated/recalls': typeof AppAuthenticatedRecallsRoute
  '/app/_authenticated/reports': typeof AppAuthenticatedReportsRoute
  '/app/_authenticated/settings': typeof AppAuthenticatedSettingsRoute
  '/app/p/$token': typeof AppPTokenRoute
  '/api/public/hooks/cashfree': typeof ApiPublicHooksCashfreeRoute
  '/api/public/hooks/meta-leads': typeof ApiPublicHooksMetaLeadsRoute
  '/api/public/hooks/meta-messages': typeof ApiPublicHooksMetaMessagesRoute
  '/api/public/hooks/meta-oauth-callback': typeof ApiPublicHooksMetaOauthCallbackRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/app/_authenticated/patients/$patientId': typeof AppAuthenticatedPatientsPatientIdRoute
  '/app/_authenticated/patients/': typeof AppAuthenticatedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/app'
    | '/app/auth'
    | '/app/book'
    | '/app/join'
    | '/app/onboarding'
    | '/app/'
    | '/app/access-denied'
    | '/app/activity'
    | '/app/appointments'
    | '/app/automations'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/leads'
    | '/app/recalls'
    | '/app/reports'
    | '/app/settings'
    | '/app/p/$token'
    | '/api/public/hooks/cashfree'
    | '/api/public/hooks/meta-leads'
    | '/api/public/hooks/meta-messages'
    | '/api/public/hooks/meta-oauth-callback'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/run-reminders'
    | '/api/public/hooks/whatsapp'
    | '/app/patients/$patientId'
    | '/app/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/app'
    | '/app/auth'
    | '/app/book'
    | '/app/join'
    | '/app/onboarding'
    | '/app/access-denied'
    | '/app/activity'
    | '/app/appointments'
    | '/app/automations'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/leads'
    | '/app/recalls'
    | '/app/reports'
    | '/app/settings'
    | '/app/p/$token'
    | '/api/public/hooks/cashfree'
    | '/api/public/hooks/meta-leads'
    | '/api/public/hooks/meta-messages'
    | '/api/public/hooks/meta-oauth-callback'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/run-reminders'
    | '/api/public/hooks/whatsapp'
    | '/app/patients/$patientId'
    | '/app/patients'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/app/_authenticated'
    | '/app/auth'
    | '/app/book'
    | '/app/join'
    | '/app/onboarding'
    | '/app/'
    | '/app/_authenticated/access-denied'
    | '/app/_authenticated/activity'
    | '/app/_authenticated/appointments'
    | '/app/_authenticated/automations'
    | '/app/_authenticated/billing'
    | '/app/_authenticated/dashboard'
    | '/app/_authenticated/inbox'
    | '/app/_authenticated/leads'
    | '/app/_authenticated/recalls'
    | '/app/_authenticated/reports'
    | '/app/_authenticated/settings'
    | '/app/p/$token'
    | '/api/public/hooks/cashfree'
    | '/api/public/hooks/meta-leads'
    | '/api/public/hooks/meta-messages'
    | '/api/public/hooks/meta-oauth-callback'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/run-reminders'
    | '/api/public/hooks/whatsapp'
    | '/app/_authenticated/patients/$patientId'
    | '/app/_authenticated/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppAuthRoute: typeof AppAuthRoute
  AppBookRoute: typeof AppBookRoute
  AppJoinRoute: typeof AppJoinRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPTokenRoute: typeof AppPTokenRoute
  ApiPublicHooksCashfreeRoute: typeof ApiPublicHooksCashfreeRoute
  ApiPublicHooksMetaLeadsRoute: typeof ApiPublicHooksMetaLeadsRoute
  ApiPublicHooksMetaMessagesRoute: typeof ApiPublicHooksMetaMessagesRoute
  ApiPublicHooksMetaOauthCallbackRoute: typeof ApiPublicHooksMetaOauthCallbackRoute
  ApiPublicHooksRazorpayRoute: typeof ApiPublicHooksRazorpayRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
  ApiPublicHooksWhatsappRoute: typeof ApiPublicHooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth': {
      id: '/app/auth'
      path: '/app/auth'
      fullPath: '/app/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book': {
      id: '/app/book'
      path: '/app/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/join': {
      id: '/app/join'
      path: '/app/join'
      fullPath: '/app/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/access-denied': {
      id: '/app/_authenticated/access-denied'
      path: '/access-denied'
      fullPath: '/app/access-denied'
      preLoaderRoute: typeof AppAuthenticatedAccessDeniedRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/activity': {
      id: '/app/_authenticated/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppAuthenticatedActivityRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/appointments': {
      id: '/app/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAuthenticatedAppointmentsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automations': {
      id: '/app/_authenticated/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAuthenticatedAutomationsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/billing': {
      id: '/app/_authenticated/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppAuthenticatedBillingRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/dashboard': {
      id: '/app/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAuthenticatedDashboardRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/inbox': {
      id: '/app/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppAuthenticatedInboxRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/leads': {
      id: '/app/_authenticated/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppAuthenticatedLeadsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/recalls': {
      id: '/app/_authenticated/recalls'
      path: '/recalls'
      fullPath: '/app/recalls'
      preLoaderRoute: typeof AppAuthenticatedRecallsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/reports': {
      id: '/app/_authenticated/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppAuthenticatedReportsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings': {
      id: '/app/_authenticated/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthenticatedSettingsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/p/$token': {
      id: '/app/p/$token'
      path: '/app/p/$token'
      fullPath: '/app/p/$token'
      preLoaderRoute: typeof AppPTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cashfree': {
      id: '/api/public/hooks/cashfree'
      path: '/api/public/hooks/cashfree'
      fullPath: '/api/public/hooks/cashfree'
      preLoaderRoute: typeof ApiPublicHooksCashfreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-leads': {
      id: '/api/public/hooks/meta-leads'
      path: '/api/public/hooks/meta-leads'
      fullPath: '/api/public/hooks/meta-leads'
      preLoaderRoute: typeof ApiPublicHooksMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-messages': {
      id: '/api/public/hooks/meta-messages'
      path: '/api/public/hooks/meta-messages'
      fullPath: '/api/public/hooks/meta-messages'
      preLoaderRoute: typeof ApiPublicHooksMetaMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-oauth-callback': {
      id: '/api/public/hooks/meta-oauth-callback'
      path: '/api/public/hooks/meta-oauth-callback'
      fullPath: '/api/public/hooks/meta-oauth-callback'
      preLoaderRoute: typeof ApiPublicHooksMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/razorpay': {
      id: '/api/public/hooks/razorpay'
      path: '/api/public/hooks/razorpay'
      fullPath: '/api/public/hooks/razorpay'
      preLoaderRoute: typeof ApiPublicHooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp': {
      id: '/api/public/hooks/whatsapp'
      path: '/api/public/hooks/whatsapp'
      fullPath: '/api/public/hooks/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/patients/': {
      id: '/app/_authenticated/patients/'
      path: '/patients'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof AppAuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/patients/$patientId': {
      id: '/app/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/app/patients/$patientId'
      preLoaderRoute: typeof AppAuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedAccessDeniedRoute: typeof AppAuthenticatedAccessDeniedRoute
  AppAuthenticatedActivityRoute: typeof AppAuthenticatedActivityRoute
  AppAuthenticatedAppointmentsRoute: typeof AppAuthenticatedAppointmentsRoute
  AppAuthenticatedAutomationsRoute: typeof AppAuthenticatedAutomationsRoute
  AppAuthenticatedBillingRoute: typeof AppAuthenticatedBillingRoute
  AppAuthenticatedDashboardRoute: typeof AppAuthenticatedDashboardRoute
  AppAuthenticatedInboxRoute: typeof AppAuthenticatedInboxRoute
  AppAuthenticatedLeadsRoute: typeof AppAuthenticatedLeadsRoute
  AppAuthenticatedRecallsRoute: typeof AppAuthenticatedRecallsRoute
  AppAuthenticatedReportsRoute: typeof AppAuthenticatedReportsRoute
  AppAuthenticatedSettingsRoute: typeof AppAuthenticatedSettingsRoute
  AppAuthenticatedPatientsPatientIdRoute: typeof AppAuthenticatedPatientsPatientIdRoute
  AppAuthenticatedPatientsIndexRoute: typeof AppAuthenticatedPatientsIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedAccessDeniedRoute: AppAuthenticatedAccessDeniedRoute,
  AppAuthenticatedActivityRoute: AppAuthenticatedActivityRoute,
  AppAuthenticatedAppointmentsRoute: AppAuthenticatedAppointmentsRoute,
  AppAuthenticatedAutomationsRoute: AppAuthenticatedAutomationsRoute,
  AppAuthenticatedBillingRoute: AppAuthenticatedBillingRoute,
  AppAuthenticatedDashboardRoute: AppAuthenticatedDashboardRoute,
  AppAuthenticatedInboxRoute: AppAuthenticatedInboxRoute,
  AppAuthenticatedLeadsRoute: AppAuthenticatedLeadsRoute,
  AppAuthenticatedRecallsRoute: AppAuthenticatedRecallsRoute,
  AppAuthenticatedReportsRoute: AppAuthenticatedReportsRoute,
  AppAuthenticatedSettingsRoute: AppAuthenticatedSettingsRoute,
  AppAuthenticatedPatientsPatientIdRoute:
    AppAuthenticatedPatientsPatientIdRoute,
  AppAuthenticatedPatientsIndexRoute: AppAuthenticatedPatientsIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppAuthRoute: AppAuthRoute,
  AppBookRoute: AppBookRoute,
  AppJoinRoute: AppJoinRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppPTokenRoute: AppPTokenRoute,
  ApiPublicHooksCashfreeRoute: ApiPublicHooksCashfreeRoute,
  ApiPublicHooksMetaLeadsRoute: ApiPublicHooksMetaLeadsRoute,
  ApiPublicHooksMetaMessagesRoute: ApiPublicHooksMetaMessagesRoute,
  ApiPublicHooksMetaOauthCallbackRoute: ApiPublicHooksMetaOauthCallbackRoute,
  ApiPublicHooksRazorpayRoute: ApiPublicHooksRazorpayRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
  ApiPublicHooksWhatsappRoute: ApiPublicHooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
