/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as ApiPublicHooksCashfreeRouteImport } from './routes/api/public/hooks/cashfree'
import { Route as ApiPublicHooksMetaLeadsRouteImport } from './routes/api/public/hooks/meta-leads'
import { Route as ApiPublicHooksMetaOauthCallbackRouteImport } from './routes/api/public/hooks/meta-oauth-callback'
import { Route as ApiPublicHooksRazorpayRouteImport } from './routes/api/public/hooks/razorpay'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'
import { Route as ApiPublicHooksWhatsappRouteImport } from './routes/api/public/hooks/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksCashfreeRoute = ApiPublicHooksCashfreeRouteImport.update({
  id: '/api/public/hooks/cashfree',
  path: '/api/public/hooks/cashfree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMetaLeadsRoute = ApiPublicHooksMetaLeadsRouteImport.update({
  id: '/api/public/hooks/meta-leads',
  path: '/api/public/hooks/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMetaOauthCallbackRoute =
  ApiPublicHooksMetaOauthCallbackRouteImport.update({
    id: '/api/public/hooks/meta-oauth-callback',
    path: '/api/public/hooks/meta-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRazorpayRoute = ApiPublicHooksRazorpayRouteImport.update({
  id: '/api/public/hooks/razorpay',
  path: '/api/public/hooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRoute = ApiPublicHooksWhatsappRouteImport.update({
  id: '/api/public/hooks/whatsapp',
  path: '/api/public/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/hooks/cashfree': typeof ApiPublicHooksCashfreeRoute
  '/api/public/hooks/meta-leads': typeof ApiPublicHooksMetaLeadsRoute
  '/api/public/hooks/meta-oauth-callback': typeof ApiPublicHooksMetaOauthCallbackRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/api/public/hooks/cashfree': typeof ApiPublicHooksCashfreeRoute
  '/api/public/hooks/meta-leads': typeof ApiPublicHooksMetaLeadsRoute
  '/api/public/hooks/meta-oauth-callback': typeof ApiPublicHooksMetaOauthCallbackRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/hooks/cashfree': typeof ApiPublicHooksCashfreeRoute
  '/api/public/hooks/meta-leads': typeof ApiPublicHooksMetaLeadsRoute
  '/api/public/hooks/meta-oauth-callback': typeof ApiPublicHooksMetaOauthCallbackRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/automations'
    | '/billing'
    | '/dashboard'
    | '/leads'
    | '/reports'
    | '/settings'
    | '/patients/$patientId'
    | '/patients/'
    | '/api/public/hooks/cashfree'
    | '/api/public/hooks/meta-leads'
    | '/api/public/hooks/meta-oauth-callback'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/run-reminders'
    | '/api/public/hooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/appointments'
    | '/automations'
    | '/billing'
    | '/dashboard'
    | '/leads'
    | '/reports'
    | '/settings'
    | '/patients/$patientId'
    | '/patients'
    | '/api/public/hooks/cashfree'
    | '/api/public/hooks/meta-leads'
    | '/api/public/hooks/meta-oauth-callback'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/run-reminders'
    | '/api/public/hooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appointments'
    | '/_authenticated/automations'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/'
    | '/api/public/hooks/cashfree'
    | '/api/public/hooks/meta-leads'
    | '/api/public/hooks/meta-oauth-callback'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/run-reminders'
    | '/api/public/hooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksCashfreeRoute: typeof ApiPublicHooksCashfreeRoute
  ApiPublicHooksMetaLeadsRoute: typeof ApiPublicHooksMetaLeadsRoute
  ApiPublicHooksMetaOauthCallbackRoute: typeof ApiPublicHooksMetaOauthCallbackRoute
  ApiPublicHooksRazorpayRoute: typeof ApiPublicHooksRazorpayRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
  ApiPublicHooksWhatsappRoute: typeof ApiPublicHooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/cashfree': {
      id: '/api/public/hooks/cashfree'
      path: '/api/public/hooks/cashfree'
      fullPath: '/api/public/hooks/cashfree'
      preLoaderRoute: typeof ApiPublicHooksCashfreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-leads': {
      id: '/api/public/hooks/meta-leads'
      path: '/api/public/hooks/meta-leads'
      fullPath: '/api/public/hooks/meta-leads'
      preLoaderRoute: typeof ApiPublicHooksMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-oauth-callback': {
      id: '/api/public/hooks/meta-oauth-callback'
      path: '/api/public/hooks/meta-oauth-callback'
      fullPath: '/api/public/hooks/meta-oauth-callback'
      preLoaderRoute: typeof ApiPublicHooksMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/razorpay': {
      id: '/api/public/hooks/razorpay'
      path: '/api/public/hooks/razorpay'
      fullPath: '/api/public/hooks/razorpay'
      preLoaderRoute: typeof ApiPublicHooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp': {
      id: '/api/public/hooks/whatsapp'
      path: '/api/public/hooks/whatsapp'
      fullPath: '/api/public/hooks/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksCashfreeRoute: ApiPublicHooksCashfreeRoute,
  ApiPublicHooksMetaLeadsRoute: ApiPublicHooksMetaLeadsRoute,
  ApiPublicHooksMetaOauthCallbackRoute: ApiPublicHooksMetaOauthCallbackRoute,
  ApiPublicHooksRazorpayRoute: ApiPublicHooksRazorpayRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
  ApiPublicHooksWhatsappRoute: ApiPublicHooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
